{
 "title": "PDT-Scapa-1",
 "tags": [
  "netconf",
  "open-nti",
  "PyEz"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DUT Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mode(\"value_str\") FROM /($host_regex).version/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Routing Engine statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RE CPU Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host_regex$/",
     "query": "select 100 - mean(value) from /($host_regex).chassis.routing-engine.*.cpu-idle/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " -100" ], "type": "math" }
      ]
     ],
     "series": "/$host_regex.chassis.routing-engine.*.cpu-idle/"
    }
   ]
  },
  {
   "title": "RE - Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).chassis.routing-engine.*.memory-buffer-utilization/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.chassis.routing-engine.*.memory-buffer-utilization/"
    }
   ]
  },
  { "title": "Routing Table Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active routes (inet.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.0.actives/"
    }
   ]
  },
  {
   "title": "Active routes (inet.3)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.actives/"
    }
   ]
  },
  {
   "title": "Actives routes (bgp.l3vpn.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.actives/"
    }
   ]
  },
  {
   "title": "Hidden routes (inet.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.0.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (inet.3)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (bgp.l3vpn.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
    }
   ]
  },
  {
   "title": "Active routes (inet6.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet6.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (inet6.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet6.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
    }
   ]
  },
  {
   "title": "Active routes (mpls.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.mpls.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (mpls.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.mpls.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
    }
   ]
  },
  {
   "title": "Active routes (inetcolor.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inetcolor.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (inetcolor.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inetcolor.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
    }
   ]
  },
  {
   "title": "Active routes (inet6color.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet6color.0.actives/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.inet.3.hidden/"
    }
   ]
  },
  {
   "title": "Hidden routes (inet6color.0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).route-table.summary.inet6color.0.hidden/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
    }
   ]
  },
  { "title": "RE PROCESSES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "RPD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.rpd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.rpd-SIZE/"
    }
   ]
  },
  {
   "title": "RPD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.rpd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DCD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.dcd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.dcd-SIZE/"
    }
   ]
  },
  {
   "title": "DCD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.dcd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "COSD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.cosd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.cosd-SIZE/"
    }
   ]
  },
  {
   "title": "COSD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.cosd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MIB2D SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mib2d-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.mib2d-SIZE/"
    }
   ]
  },
  {
   "title": "MIB2D CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mib2d-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNMPD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.snmpd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.snmpd-SIZE/"
    }
   ]
  },
  {
   "title": "SNMPD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.snmpd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DFWD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.dfwd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.dfwd-SIZE/"
    }
   ]
  },
  {
   "title": "DFWD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.dfwd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SAMPLED SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.sampled-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "SAMPLED CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.sampled-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassisd SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.chassisd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "CHASSISD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.chassisd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LACPD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.lacpd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "LACPD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.lacpd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "L2CPD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.l2cpd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "L2CPD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.l2cpd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JSD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.jsd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "JSD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.jsd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NA-GRPCD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.grpc-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "NA-GRPCD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.grpc-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AGENTD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.agentd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "AGENTD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.agentd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTTD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mqtt-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "MQTTD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mqtt-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MGD-API SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mgdapi-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "MGD-API CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.mgdapi-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XMLPROXYD SIZE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.xmlproxyd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "XMLPROXYD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).re.memory.xmlproxyd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PFE TRANSIT STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "collapsed": true,
   "panels": [
    {
     "title": "pfe-packets (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-traffic-stats.pfe-.*-packets/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-traffic-stats.pfe-.*-packets/"
      }
     ]
    },
    {
     "title": "pfe-pps (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).pfe-general-stats.aggregated.pfe-traffic-stats.*-pps/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-traffic-stats.*-pps/"
      }
     ]
    },
    {
     "title": "PFE bits-to-test-discards (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.bits-to-test-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.bits-to-test-discard/"
      }
     ]
    },
    {
     "title": "PFE data-error-discard (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.data-error-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.data-error-discard/"
      }
     ]
    },
    {
     "title": "PFE stack-underflow-discard (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-underflow-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-underflow-discard/"
      }
     ]
    },
    {
     "title": "PFE stack-overflow-discard (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-overflow-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-overflow-discard/"
      }
     ]
    },
    {
     "title": "PFE bad-route-discards (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 199 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.bad-route-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.bad-route-discard/"
      }
     ]
    },
    {
     "title": "PFE nexthop-discard (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 199 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex)..pfe-general-stats.aggregated.pfe-hardware-discards-stats.nexthop-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.nexthop-discard/"
      }
     ]
    },
    {
     "title": "PFE invalid-iif-discards (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 206 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.invalid-iif-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.invalid-iif-discard/"
      }
     ]
    },
    {
     "title": "PFE info-cell-discards (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 206 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.info-cell-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.info-cell-discard/"
      }
     ]
    },
    {
     "title": "PFE fabric-discards (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.fabric-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.fabric-discard/"
      }
     ]
    },
    {
     "title": "PFE timeout-discads (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.timeout-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.timeout-discard/"
      }
     ]
    },
    {
     "title": "PFE truncated-key-discard (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 220 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(delta) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.truncated-key-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.truncated-key-discard/"
      }
     ]
    }
   ]
  },
  { "title": "PFE Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "FPC CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 179 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spc-34-ptx1k.fpc.slot0.resource.used-heap-percent",
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-cpu-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.resource.used-heap-mem-percent/"
    }
   ]
  },
  {
   "title": "FPC Heap Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 179 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-heap-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-ifl-counter-percent/"
    }
   ]
  },
  {
   "title": "FPC Buffer Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-buffer-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-filter-counter-percent/"
    }
   ]
  },
  { "title": "BGP STATISTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 } },
  {
   "title": "bgp peer-count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).protocols.bgp.summary.peer-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  },
  {
   "title": "bgp down-peer-count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 204 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).protocols.bgp.summary.down-peer-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.down-peer-count/"
    }
   ]
  },
  {
   "title": "RSVP Ingress LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Ingress.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.group-count/"
    }
   ]
  },
  {
   "title": "RSVP Transit LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 211 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Transit.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  },
  {
   "title": "RSVP Egress LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Egress.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  }
 ]
}